<MenuBoxes, NewPlant, CombineHorizontalBoxes>:
    orientation: "horizontal"

    canvas:
        Rectangle:
            pos:self.pos
            size:self.size
            source: 'green_background.png'

<PlantBoxes, MainBoxes, CombineAllBoxes>:
    orientation: "vertical"

    canvas:
        Rectangle:
            pos:self.pos
            size:self.size
            source: 'green_background.png'